DistanceVolume_CL
plunkettscott/interact-sound pull request #32
Opened 2021-10-12 19:08 UTC by pingouinn

2021-10-20 15:04 UTC, plunkettscott requested changes
Few minor house cleaning things, otherwise looks good for an experimental build.

2021-10-20 15:04 UTC, plunkettscott commented on client/html/index.html
> +				        if (event.data.transactionType == "volume") {
Let's fix the alignment of these conditionals

2021-10-20 15:04 UTC, plunkettscott commented on client/main.lua
> +        if tonumber(otherPlayerCoords) then
More alignment issues

2021-10-20 15:07 UTC, plunkettscott commented on client/main.lua
> +        if tonumber(otherPlayerCoords) then
Make sure the conditionals align with `distance` below.

2021-10-21 11:51 UTC, pingouinn commented
I will do that, sorry for the cleaning problems i have made the commit with my phone haha !

2024-02-27 21:38 UTC, closed without merging